# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMakespaceAutomationtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_makespaceAutomationtest(self):
    self.driver.get("https://dev.mksp.co/")
    self.driver.set_window_size(1920, 847)
    self.driver.find_element(By.CSS_SELECTOR, ".zip-input:nth-child(3) .makespace-ui-library-14vob52").click()
    self.driver.find_element(By.CSS_SELECTOR, ".zip-input:nth-child(3) .makespace-ui-library-14vob52").send_keys("10038")
    self.driver.find_element(By.CSS_SELECTOR, ".zip-input:nth-child(3) .e10p5ni92").click()
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-8knxur:nth-child(2) .cardside .e165yw023").click()
    self.driver.find_element(By.NAME, "bin").click()
    self.driver.find_element(By.NAME, "bin").send_keys("4")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .e165yw023").click()
    self.driver.find_element(By.CSS_SELECTOR, ".epfibpa8").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".epfibpa8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n1h5a8:nth-child(1) .css-x1gxla:nth-child(1) > .css-79elbk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n1h5a8:nth-child(2) .css-x1gxla:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n1h5a8:nth-child(3) .css-x1gxla:nth-child(1) > .css-79elbk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n1h5a8:nth-child(4) .css-x1gxla:nth-child(1) > .css-79elbk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-x1gxla:nth-child(1) > .css-79elbk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1oldnow").click()
    self.driver.find_element(By.NAME, "fullName").click()
    self.driver.find_element(By.NAME, "fullName").send_keys("MakeSpace Automation")
    self.driver.find_element(By.NAME, "phone").send_keys("(234) 567-8989")
    self.driver.find_element(By.NAME, "email").send_keys("MakeSpaceAutomation@mailinator.com")
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-13lrsdm:nth-child(2) > .makespace-ui-library-14ovu1w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-105ote56").click()
    self.driver.find_element(By.NAME, "address_pretty").click()
    self.driver.find_element(By.NAME, "address_pretty").send_keys("123 William Street")
    element = self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-1sre8bb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nv2uc41 .makespace-ui-library-1rat6ui").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nv2uc41 .makespace-ui-library-1rat6ui").send_keys("22")
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-14ygzkk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-14ygzkk").send_keys("None")
    self.driver.find_element(By.CSS_SELECTOR, ".css-nv2uc43").click()
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-1dee5ie").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(4) > .react-datepicker__day--mon").click()
    self.driver.find_element(By.NAME, "Time").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-wkjcpv1").click()
    self.driver.switch_to.frame(2)
    self.driver.find_element(By.NAME, "cardnumber").click()
    self.driver.find_element(By.NAME, "cardnumber").send_keys("4111 1111 1111 1111")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-1i98359:nth-child(2) .makespace-ui-library-1r2yix9").click()
    self.driver.switch_to.frame(3)
    self.driver.find_element(By.NAME, "exp-date").send_keys("02 / 22")
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(4)
    self.driver.find_element(By.NAME, "cvc").send_keys("222")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".makespace-ui-library-14ovu1w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-nlchn23").click()
  
